# config.yaml

# coins_file: "coins_bybit_spot.txt"
# coins_file: "test_10.txt"
# coins_file: "test_30.txt"
coins_file: "test_120.txt"
coins_per_process: 10

redis:
  host: "localhost"
  port: 6379
  db: 0

proxy:
  rest_file: "proxies_bybit_h.txt"
  ws_file: "proxies_bybit_s.txt"
  # rest_file: ""                  # отключаем REST-прокси
  # ws_file: ""                    # отключаем WS-прокси

update:
  rest_interval_sec: 60
  max_ws_reconnect_attempts: 3
  # Глубина стакана для подписки по WebSocket. Тут можно поставить только 1, 50 или 200 по документаций.
  orderbook_depth: 200

logging:
  level: "INFO"
  # level: "DEBUG"
  to_file: true
  log_dir: "logs"

features:
  enable_rest: false
  enable_ws: true
